version: '3'

services:

  web:
    container_name: simpsons-prod-container
    build:
      context: .
      # dockerfile is an nginx image
      dockerfile: ./Dockerfile.prod
    ports:
      - '80:80'
    networks:
      - default

networks:
  default: