version: '3'

services:

  web:
    container_name: simpsons-dev-container
    build:
      context: .
<<<<<<< HEAD
      # dockerfile is an nginx image
      dockerfile: ./Dockerfile.prod
=======
      dockerfile: ./Dockerfile.dev
>>>>>>> jhd/dev/revamp
    ports:
      - '80:80'
    networks:
      - default

networks:
  default:
